"""
AI Decision Engine for Polymarket Trading Agent
"""
import logging
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
from enum import Enum

from config.settings import trading_config
from core.market_data import MarketSnapshot, MarketDataProcessor

logger = logging.getLogger(__name__)


class TradeAction(Enum):
    BUY_YES = "buy_yes"
    BUY_NO = "buy_no"
    SELL_YES = "sell_yes"
    SELL_NO = "sell_no"
    HOLD = "hold"


@dataclass
class TradeSignal:
    """Trading signal generated by AI"""
    market_id: str
    action: TradeAction
    confidence: float
    size: float
    reason: str


class DecisionEngine:
    """AI decision engine for trading"""
    
    def __init__(self, market_processor: MarketDataProcessor):
        self.market_processor = market_processor
        self.active_positions: Dict[str, Dict] = {}
    
    def analyze_market(self, market: MarketSnapshot) -> TradeSignal:
        """Analyze a market and generate trading signal"""
        market_id = market.market_id
        
        # Get technical indicators
        momentum = self.market_processor.get_price_momentum(market_id)
        volatility = self.market_processor.get_volatility(market_id)
        
        # AI Analysis logic
        signal = self._generate_signal(market, momentum, volatility)
        
        return signal
    
    def _generate_signal(self, market: MarketSnapshot, momentum: float, volatility: float) -> TradeSignal:
        """Generate trading signal based on market analysis"""
        
        # Strategy: Momentum-based trading with mean reversion
        confidence = 0.0
        action = TradeAction.HOLD
        reason = "No clear signal"
        
        # Check if we have an active position
        has_position = market.market_id in self.active_positions
        
        # Momentum strategy
        if momentum > 0.05:  # Strong upward momentum
            if market.yes_price < 0.8:  # Not overbought
                confidence = min(0.5 + momentum, 0.95)
                action = TradeAction.BUY_YES
                reason = f"Strong upward momentum ({momentum:.2%}) with room to grow"
        elif momentum < -0.05:  # Strong downward momentum
            if market.no_price < 0.8:  # Not overbought on NO
                confidence = min(0.5 + abs(momentum), 0.95)
                action = TradeAction.BUY_NO
                reason = f"Strong downward momentum ({momentum:.2%}) with room on NO side"
        
        # Mean reversion for extreme prices
        if market.yes_price > 0.9 and volatility > 0.05:
            confidence = 0.7
            action = TradeAction.BUY_NO
            reason = "Mean reversion: YES overbought, high volatility"
        elif market.no_price > 0.9 and volatility > 0.05:
            confidence = 0.7
            action = TradeAction.BUY_YES
            reason = "Mean reversion: NO overbought, high volatility"
        
        # Volume confirmation
        if market.volume > 10000 and confidence > 0:
            confidence = min(confidence + 0.1, 0.95)
            reason += " (high volume confirmation)"
        
        # Calculate position size based on confidence
        size = self._calculate_position_size(confidence, market)
        
        return TradeSignal(
            market_id=market.market_id,
            action=action,
            confidence=confidence,
            size=size,
            reason=reason
        )
    
    def _calculate_position_size(self, confidence: float, market: MarketSnapshot) -> float:
        """Calculate position size based on confidence and risk parameters"""
        if confidence < trading_config.min_confidence:
            return 0.0
        
        # Kelly Criterion-inspired sizing
        win_prob = confidence
        loss_prob = 1 - confidence
        
        # Conservative Kelly fraction
        kelly_fraction = 0.25
        
        # Base position size
        base_size = trading_config.max_position_size * trading_config.risk_per_trade
        
        # Scale by confidence
        position_size = base_size * confidence * kelly_fraction
        
        # Ensure we don't exceed max position
        return min(position_size, trading_config.max_position_size)
    
    def should_execute_trade(self, signal: TradeSignal) -> bool:
        """Determine if a trade should be executed"""
        if signal.confidence < trading_config.min_confidence:
            return False
        
        if signal.size <= 0:
            return False
        
        if signal.action == TradeAction.HOLD:
            return False
        
        return True
    
    def update_position(self, market_id: str, position_data: Dict):
        """Update active position tracking"""
        self.active_positions[market_id] = position_data
    
    def close_position(self, market_id: str):
        """Remove position from tracking"""
        if market_id in self.active_positions:
            del self.active_positions[market_id]
    
    def get_active_positions(self) -> Dict[str, Dict]:
        """Get all active positions"""
        return self.active_positions.copy()
